PorygonAPI/Porygon2

- src/main/java/edu/fatec/Porygon/controller/PortalController.java
- src/main/java/edu/fatec/Porygon/model/Portal.java
- src/main/java/edu/fatec/Porygon/service/PortalService.java
- src/main/resources/application.properties
- src/main/resources/templates/portal.html
PYG-7:Build: Adicionado Labels do Web Scraping no Front e Salvamento automático da Data.
PYG-30:Refactor: Adicionado colunas do Web Scraping na Tabela Portal.
> PYG-2 PYG-7 PYG-30 (Configuração do Webscraping - Backend e FrontEnd) e (Adicionar colunas da configuração do Webscraping na tabela portal no banco)

- CONTRIBUTING.md
- README.md
Atualizei o nome do João Bispo para João Pedro;
Atualizei os requisitos não funcionais no Product Backlog, conforme orientação da profª Juliana;
Atualizei o arquivo de contribuição de commits, adicionando as informações da Carla no Jira.
> docs(readme/contributing): atualiza o backlog das sprints e os padrões de commit, branch e pull request

- src/main/java/edu/fatec/Porygon/controller/PortalController.java
Bastou inserir um else para identificar o portal já existente ;)
> PYG-2 PYG-26 fix: arrumando data_criacao sendo apagada pos edicao

- src/main/java/edu/fatec/Porygon/controller/PortalController.java
- src/main/resources/templates/index.html
- src/main/resources/templates/portal.html
Adicionei uma verificação para Tag, então memso se não houver tags cadastradas ele não irá bugar , assim não será necessário modificar a tela quando incluirmos a implementação de tag no projeto.
> PYG-2-PYG-6-fix<PortalController e html>portal vem com ativo cadastrado

- src/main/resources/templates/api.html
- src/main/resources/templates/index.html
- src/main/resources/templates/portal.html
Ainda não é possivel acessar direto da aplicação pois não tem controller para dizer a rota , no backend será configurado
> PYG-3-PYG-33-feat<front> Criando html da tela do API segundo o frame disponibilizado

- src/main/java/edu/fatec/Porygon/model/Portal.java
Adicionado a coluna de última atualização do WebScraping!
> PYG-36/PYG-47/feat/Registrar-Última-Execução-do-WebScraping

- src/main/java/edu/fatec/Porygon/controller/ApiController.java
- src/main/resources/templates/api.html
> PYG-3-PYG-41-feat<back e front> Criar validação para usuário quando tentar cadastrar uma api com o mesmo nome ou URL

- src/main/java/edu/fatec/Porygon/model/Api.java
- src/main/java/edu/fatec/Porygon/model/ApiDados.java
- src/main/resources/application.properties
[Criado a tabela de API_Dados e adicionado as colunas (data-criacao e ultima-atualizacao) na tabela de API
> PYG-36/PYG-46/Feat/Reconfiguracao-Banco-de-Dados

- src/main/java/edu/fatec/Porygon/PorygonApplication.java
- src/main/java/edu/fatec/Porygon/controller/PortalController.java
- src/main/java/edu/fatec/Porygon/model/Portal.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/resources/application.properties
Alteração do webscraping para que o mesmo ocorra apenas no cadastramento inicial do portal e seja executado regularmente conforme agendamento (Diário, semanal e mensal)
> pyg-36-pyg-49-feat-Alterar-Ocorrencia-do-Webscraping-v1

- src/main/java/edu/fatec/Porygon/PorygonApplication.java
- src/main/java/edu/fatec/Porygon/model/Portal.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/resources/application.properties
- src/main/resources/templates/api.html
- src/main/resources/templates/index.html
- src/main/resources/templates/portal.html
Foram padronizadas as tabelas com a mesma classe de estilo
Foram padronizados os espaçamentos entre os form
Adiconado um tema para página
Adicionado um ícone em vez de Projeto no header
Correção da Navbar na tela da API
> style/frontend criando um layout mais atrativo para telas criadas até o momento

- src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- src/main/java/edu/fatec/Porygon/repository/NoticiaRepository.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/java/edu/fatec/Porygon/service/NoticiaService.java
- src/main/resources/application.properties
- src/main/resources/templates/index.html
Implementada a lógica backend para consultar notícias filtradas pelo intervalo de datas selecionado.
> Pyg 17 pyg 39 implementar a logica backend para consultar noticias filtradas pelo intervalo de datas selecionado back end

- src/main/java/edu/fatec/Porygon/service/ApiRotinaService.java
- src/main/java/edu/fatec/Porygon/service/ApiService.java
Principais mudanças no 'ApiService.java': 
-> Importado o AgendadorRepository para consultar os agendadores;
-> No método 'salvarOuAtualizar', se não houver um agendador definido, a API é configurada para usar o agendador "diário" (id = 1), sendo essa a configuração 'default' ao cadastrar APIs;
-> Implementado o método 'verificarEAtualizarApis', que verifica se as APIs ativas precisam ser atualizadas com base na periodicidade do agendador.
> PYG-3-PYG-34(feat)Configurar-Rotina-de-Periodicidade-Tabela-de-Agendamento-API

- src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- src/main/java/edu/fatec/Porygon/repository/NoticiaRepository.java
- src/main/java/edu/fatec/Porygon/service/NoticiaService.java
- src/main/resources/templates/index.html
Como nosso banco considera o Date e no nosso código usamos LocalDate, quando consultávamos as datas o front mostrava com 1 dia a menos, por conta do fuso. Na branch do Vitor a lista de notícias estava com a data certa, mas o modal estava com a data errada. Crei a fix para adicionar o fuso também no modal
> PYG-17 PYG-39 fix(index) adiciona fuso para retornar as datas corretas na lista de notícias filtradas e no modal

- src/main/resources/templates/portal.html
A tela onde listamos os portais está sem a coluna Tags, só adicionei para ficar igual as outras
PULL FEITO - PRONTO PARA MERGE
> PYG-81 style(coluna): Adicionado coluna Tags na tela portal

- src/main/java/edu/fatec/Porygon/controller/PortalController.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/resources/templates/portal.html
No momento de salvar a noticia é verificado se ele possue  título, jornalista e conteúdo, caso não possua nenhum deles ao mesmo tempo a noticia é desconsiderada e não salva
PULL FEITO - PRONTO PARA MERGE
> PYG-81 feat(condicional): Criar verificacao de noticias nulas

- src/main/resources/templates/api.html
> PYG-81 feat/style(api.html):  implementar um loading quando a api é cadastrada

- src/main/java/edu/fatec/Porygon/model/Sinonimo.java
- src/main/java/edu/fatec/Porygon/model/Tag.java
- src/main/java/edu/fatec/Porygon/repository/SinonimoRepository.java
- src/main/java/edu/fatec/Porygon/repository/TagRepository.java
- src/main/java/edu/fatec/Porygon/service/TagScrapperService.java
- src/main/java/edu/fatec/Porygon/service/TagService.java
- src/test/java/edu/fatec/Porygon/PorygonApplicationTests.java
O `TagService` quebrou, então para a aplicação subir, reformulei para que ele refletisse as atualizações da nova tabela e o Scrapper continuasse funcionando.
- Modificações no `TagRepository`.
Criei um teste unitário para validar o relacionamento das tabelas.
> PYG-14 PYG-70 feat(tabela) criado tabela sinonimo e relacionamento com tag

- src/main/resources/templates/index.html
> PYG-93 PYG-102 style(index): retirando "Tipo" da tela de consulta de noticias

- src/main/java/edu/fatec/Porygon/controller/ApiController.java
- src/main/java/edu/fatec/Porygon/controller/ApiDadosController.java
- src/main/java/edu/fatec/Porygon/repository/ApiDadosRepository.java
- src/main/java/edu/fatec/Porygon/service/ApiDadosService.java
- src/main/resources/templates/apiDados.html
- src/test/java/edu/fatec/Porygon/PorygonApplicationTests.java
> PYG-93 PYG-107 fix(apidados): implementar logica para listar dados das apis na tela consulta

- src/main/java/edu/fatec/Porygon/controller/TagController.java
- src/main/java/edu/fatec/Porygon/repository/TagRepository.java
- src/main/java/edu/fatec/Porygon/service/TagService.java
- src/main/resources/templates/api.html
- src/main/resources/templates/apiDados.html
- src/main/resources/templates/index.html
- src/main/resources/templates/portal.html
- src/main/resources/templates/tag.html
Peço que testem para ver se está sendo salvo corretamente na tabela de Tag e se está verificando corretamente sua duplicidade.
Lembrando que a listagem delas no front virá em outra task que estou desenvolvendo.
> PYG-14 PYG-67: feature de nova tela (back/front) para cadastro de Tags e sua verificação de duplicidade

- src/main/java/edu/fatec/Porygon/controller/TagController.java
- src/main/java/edu/fatec/Porygon/service/TagService.java
- src/main/resources/templates/tag.html
A listagem segue em ordem alfabética conforme solicitado no Jira.
> PYG-14 PYG-82: Inserindo listagem de tags no front

- src/main/java/edu/fatec/Porygon/service/TagService.java
- src/main/resources/application.properties
- src/main/resources/templates/tag.html
@vmorais111 @lucasalex1203 Englobei as tasks de voces, acabei fazendo (y)
> PYG-14 PYG-68 PYG-84 PYG-87 PYG-109 fix: verificacao regionalismo

- src/main/java/edu/fatec/Porygon/controller/ApiController.java
- src/main/java/edu/fatec/Porygon/controller/PortalController.java
- src/main/java/edu/fatec/Porygon/service/ApiService.java
- src/main/java/edu/fatec/Porygon/service/PortalService.java
- src/main/resources/templates/api.html
- src/main/resources/templates/portal.html
> PYG-93 PYG-104 feat(front): tirar a obrigatoridade de descricao na api

- src/main/java/edu/fatec/Porygon/model/ApiDados.java
- src/main/java/edu/fatec/Porygon/model/Noticia.java
Tive que criar novas tabelas
Como as tags vão ser atribuidas uma vez e nunca retiradas só adicionadas das noticias e dados de api , então não faz sentido deixar o relacionamento direto em uma tabela é preciso separar.
- Vou deixar um Script para testar o relacionamento no banco (MYSQL SERVER)
- E os prints das tabelas populadas
1. APIDADOS
```sql
-- Inserindo Tags
INSERT INTO [TESTERUTH].[dbo].[tag] ([nome]) VALUES 
('Tecnologia'),
('Notícias'),
('Ciência'),
('Saúde');
-- Inserindo APIs
INSERT INTO [TESTERUTH].[dbo].[api] ([ativo], [data_criacao], [descricao], [nome], [ultima_atualizacao], [url])
VALUES 
(1, GETDATE(), 'API de Notícias sobre Tecnologia', 'TechNews API', GETDATE(), 'https://technews.example.com/api'),
(1, GETDATE(), 'API de Ciência e Saúde', 'HealthScience API', GETDATE(), …
```
> PYG-110 PYG-111 feat(banco): criar tabela para vincular tags as noticias e dados de api

- src/main/java/edu/fatec/Porygon/controller/ApiController.java
- src/main/java/edu/fatec/Porygon/controller/PortalController.java
- src/main/java/edu/fatec/Porygon/model/Api.java
- src/main/java/edu/fatec/Porygon/model/Portal.java
- src/main/java/edu/fatec/Porygon/model/Tag.java
- src/main/java/edu/fatec/Porygon/repository/ApiRepository.java
- src/main/java/edu/fatec/Porygon/repository/PortalRepository.java
- src/main/java/edu/fatec/Porygon/service/ApiService.java
- src/main/java/edu/fatec/Porygon/service/PortalService.java
- src/main/resources/templates/api.html
- src/main/resources/templates/portal.html
Precisa dropar o banco
Eu mudei muito o arquivo pára atender a funcionalidade, preciso que testes tudo e caso certo deem aprove o mais cedo possivel
OBRIGATORIO
No banco
PORTAL
API
Telas
PORTAL
API
> PYG-14 PYG-89 PYG-88 fix(banco,front e back) salvar e editar tags em portais e apis

- src/main/java/edu/fatec/Porygon/model/ApiDados.java
- src/main/java/edu/fatec/Porygon/service/ApiRotinaService.java
- src/main/java/edu/fatec/Porygon/service/ApiService.java
- src/main/resources/templates/apiDados.html
> PYG-93 PYG-106 feat(back, front, banco): adicionar coluna de data para cada dado de api

- src/main/java/edu/fatec/Porygon/model/ApiDados.java
- src/main/java/edu/fatec/Porygon/service/ApiService.java
- src/main/resources/templates/api.html
Pelo que compreendi, fiz a associação como pedido no Jira: https://porygon.atlassian.net/jira/software/c/projects/PYG/boards/5?selectedIssue=PYG-117&useStoredSettings=true
Solicitou para mexer somente com o banco e o back, então foi algo bem simples se entendi corretamente.
Pretendo pegar a task relacionada ao front também, caso ninguém tenha pego.
Já subi essa PR por conta da prioridade dela no Jira.
Fiz os testes com múltiplas tags e foi certinho também,
> PYG-110 PYG-117: Associação automática de tags com apidados

- src/main/java/edu/fatec/Porygon/model/ApiDados.java
- src/main/resources/templates/apiDados.html
- src/main/resources/templates/index.html
Ainda não tinhamos nenhum método relacionado ou algo do tipo, então só refatorei o front, retirando o input na aba de consulta de notícias e API dados
> PYG-110 PYG-120 refactor(index e apiDados.html): retira input de consulta por contem (conteudo)

- src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- src/main/java/edu/fatec/Porygon/model/ApiDados.java
- src/main/java/edu/fatec/Porygon/model/Jornalista.java
- src/main/java/edu/fatec/Porygon/model/Noticia.java
- src/main/java/edu/fatec/Porygon/model/NoticiaDTO.java
- src/main/java/edu/fatec/Porygon/repository/JornalistaRepository.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/java/edu/fatec/Porygon/service/JornalistaService.java
- src/main/resources/templates/index.html
Necessário dropar o banco.
No banco:
No Front:
> PYG-93 PYG-98 feat: criar uma tabela para jornalistas  exibir no modal

- src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- src/main/java/edu/fatec/Porygon/model/Noticia.java
- src/main/java/edu/fatec/Porygon/model/Tag.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/java/edu/fatec/Porygon/service/NoticiaService.java
- src/main/resources/templates/index.html
Reverts PorygonAPI/Porygon2#99
> Revert "PYG-16/PYG-17/fix/consulta-por-data-colunas-lista-noticias"

- src/main/java/edu/fatec/Porygon/model/Noticia.java
- src/main/java/edu/fatec/Porygon/model/Portal.java
- src/main/java/edu/fatec/Porygon/model/Tag.java
- src/main/java/edu/fatec/Porygon/repository/NoticiaRepository.java
- src/main/java/edu/fatec/Porygon/repository/PortalRepository.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/java/edu/fatec/Porygon/service/NoticiaService.java
- src/main/resources/application.properties
Feita a funcionalidade de mostrar as noticias com tag no front e quando não tiver uma tag no conteudo, mostrar que não tem.
> PYG-110 PYG-115:  Associa tag para notica se existir no conteudo

- src/main/java/edu/fatec/Porygon/PorygonApplication.java
- src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- src/main/java/edu/fatec/Porygon/model/Noticia.java
- src/main/java/edu/fatec/Porygon/model/Tag.java
- src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- src/main/java/edu/fatec/Porygon/service/NoticiaService.java
- src/main/resources/templates/index.html
Corrige a consulta por data de notícias, listando por DTO e não por entidade
image
Corrige as colunas da lista de notícias quando nenhuma notícia tem tag
> PYG-16 PYG-17 fix(noticia): corrige consulta por data e coluna de noticias

- src/main/java/edu/fatec/Porygon/controller/TagController.java
- src/main/java/edu/fatec/Porygon/repository/SinonimoRepository.java
- src/main/java/edu/fatec/Porygon/service/TagService.java
- src/main/resources/templates/tag.html
***
Sinônimo cadastrado no banco
Ao tentar cadastrar tag "Regra" é verificado se essa palavra está cadastrada como sinônimo, e oferecida a opção de cancelamento ou cadastrado para o usuário.
Tag cadastrada mesmo com registro no sinônimo
@pablohgs05  Agradeço pela ajuda ✨ 
***
> PYG-14 PYG-90: Criação da verificação de sinônimos já cadastrados.

- src/main/java/edu/fatec/Porygon/repository/ApiDadosRepository.java
- src/main/java/edu/fatec/Porygon/service/ApiRotinaService.java
- src/main/java/edu/fatec/Porygon/service/ApiService.java
- src/test/java/edu/fatec/Porygon/PorygonApplicationTests.java
Essa PR é um fix lançado para a PYG-110 PYG-112 em que arruma a atualização das tags de apidados referentes aos apis e mantem sua rotina de scrap. Em conjunto, está sendo entregue uma feat de melhoria que faz a verificação de dados duplicados (PYG-93 PYG-108).
> PYG-110 PYG-112 PYG-93 PYG-108: atualização e verificação de dados duplicados do apidados

- README.md
Atualização do burndown e mudança de escopo
> Docs/readme: atualiza o burndown sprint 3

- codebase/src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- codebase/src/main/java/edu/fatec/Porygon/model/ApiDados.java
- codebase/src/main/java/edu/fatec/Porygon/repository/TagRepository.java
- codebase/src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- codebase/src/main/java/edu/fatec/Porygon/service/NoticiaService.java
**Retirei as chamadas individuais que existiam nas rotinas do DataScrapperService para os métodos de associação das tags**
**Retirei o endpoint do controlller que chamava os métodos e não estava em uso** 
**Adicionei o método salvar , chamando ele direto do NoticiaService, concentrando a regra de negócio em um único lugar:**
_Compilei os métodos para se associação para que ele não precise passar por todo os sinonimos , mas quando encontrar o primeiro ele já atribua a tag:_
``` java
private void associarTags(Noticia noticia) {
Set<Tag> tagsPortal = new HashSet<>(tagRepository.findAllByPortais_Id(noticia.getPortal().getId())); 
Set<Tag> foundTags = encontrarTagsNoTitulo(noticia.getTitulo(), tagsPortal);
if (foundTags.isEmpty()) {
foundTags = encontrarTagsNoConteudo(noticia.getConteudo(), …
```
> PYG-122 PYG-118 perf(tag): Refatora o código para reduzir o tempo de resposta na associação de tags às notícias.

- codebase/src/main/resources/templates/index.html
- codebase/src/main/resources/templates/portal.html
Adiciona o campo , onde será exibido o filtro de busca ,as tags e as badges
Somente Front.
> PYG-18 PYG-73 feat (front): Construir campo para filtro de tags na tela da consulta de noticias

- codebase/src/main/resources/templates/apiDados.html
> PYG-22 PYG-77 feat(front): Construir campo para filtro de tags na tela da consulta de dados da api

- codebase/src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- codebase/src/main/java/edu/fatec/Porygon/repository/NoticiaRepository.java
- codebase/src/main/java/edu/fatec/Porygon/service/NoticiaService.java
- codebase/src/main/resources/application.properties
- codebase/src/main/resources/static/css/styles.css
- codebase/src/main/resources/templates/api.html
- codebase/src/main/resources/templates/apiDados.html
- codebase/src/main/resources/templates/index.html
- codebase/src/main/resources/templates/portal.html
Método para fazer as tags visiveis para serem selecionadas:
Consultei pela tag "dinheiro" e foi mostrada todas as que continham essa tag:
Busquei por uma tag que não continham nenhuma noticia:
> PYG-18 PYG-75 feat: Método para fazer a busca por tags na consulta de noticias.

- codebase/src/main/java/edu/fatec/Porygon/controller/ApiDadosController.java
- codebase/src/main/java/edu/fatec/Porygon/repository/ApiDadosRepository.java
- codebase/src/main/java/edu/fatec/Porygon/repository/SinonimoRepository.java
- codebase/src/main/java/edu/fatec/Porygon/repository/TagRepository.java
- codebase/src/main/java/edu/fatec/Porygon/service/ApiDadosService.java
- codebase/src/main/resources/templates/apiDados.html
> PYG-22 PYG-78: Trazendo busca de dados das API's através de tags

- codebase/src/main/resources/templates/api.html
Trazendo notificação de API ativado/desativado com sucesso ao front, pois o back já foi implementado.
> PYG-122 PYG-121 feat: trazendo notificação ao front de API'S

- codebase/src/main/java/edu/fatec/Porygon/config/AsyncConfig.java
- codebase/src/main/java/edu/fatec/Porygon/controller/TagController.java
- codebase/src/main/java/edu/fatec/Porygon/service/ApiRotinaService.java
- codebase/src/main/java/edu/fatec/Porygon/service/ApiService.java
- codebase/src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- codebase/src/main/java/edu/fatec/Porygon/service/TagService.java
Adicionado async nos metodos mais pesados para realizar requisicoes  sem derrubar a aplicacao
para teste seria cadastar  portais e apis e verificar o desempenho da aplicacao.
> PYG-122 PYG-128 refactor: otimiza e melhoria do desempenho do sistema

- codebase/src/main/java/edu/fatec/Porygon/controller/PortalController.java
- codebase/src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- codebase/src/main/resources/templates/portal.html
**Seletor do camilnho da noticia**
**Seletor do Título da noticia**
**Seletor do Jornalista da noticia**
**Seletor de Data da noticia**
**Seletor de Conteúdo da noticia**
Em nenhum momento o portal é salvo , a validação ocorre antes.
> PYG-122 PYG-96 feat: implementa logica e aviso para erros dos seletores

- codebase/src/main/java/edu/fatec/Porygon/controller/ApiDadosController.java
- codebase/src/main/resources/application.properties
- codebase/src/main/resources/static/css/styles.css
- codebase/src/main/resources/templates/apiDados.html
Criada uma função para apresentar as APIs filtradas de forma organizada e clara na interface do usuário. Por padrão as api's vem listadas pelo ID de modo decrescente, havendo ainda a opção (pelos novos botões presentes no modal) de o usuário fazer a pesquisa pelo nome ou pela data da ultima raspagem. Também para melhorar a visualização dos dados de cada api, foi alterado o tamanho dos modais que exibem seus conteúdos, de modo que o tamanho dos mesmos não ultrapassem a tela, utilizando de uma scroll vertical dentro do modal para melhorar sua visualização.
> PYG-21 PYG-59 feat: Exibicao das apis filtradas na tela

- codebase/src/main/java/edu/fatec/Porygon/controller/PortalController.java
- codebase/src/main/java/edu/fatec/Porygon/service/PortalService.java
Cadastrar um portal desativado ou manipuloar a data no banco e usar o o botão de ativar portal para validar a raspagem.
Ela ocorre independe do agendador , pois seria como a primeira raspgaem daquele portal
> PYG-3 PYG-38 fix: modificando metodo de alterar status para acionar raspagem quando portal ativado

- codebase/src/main/java/edu/fatec/Porygon/config/AgendadorDataLoader.java
- codebase/src/main/java/edu/fatec/Porygon/config/AsyncConfig.java
- codebase/src/main/java/edu/fatec/Porygon/config/FormatoDataLoader.java
- codebase/src/main/java/edu/fatec/Porygon/controller/ApiController.java
- codebase/src/main/java/edu/fatec/Porygon/controller/ApiDadosController.java
- codebase/src/main/java/edu/fatec/Porygon/controller/NoticiaController.java
- codebase/src/main/java/edu/fatec/Porygon/controller/PortalController.java
- codebase/src/main/java/edu/fatec/Porygon/dto/ApiDadosDTO.java
- codebase/src/main/java/edu/fatec/Porygon/repository/ApiDadosRepository.java
- codebase/src/main/java/edu/fatec/Porygon/service/ApiRotinaService.java
- codebase/src/main/java/edu/fatec/Porygon/service/ApiService.java
- codebase/src/main/java/edu/fatec/Porygon/service/DataScrapperService.java
- codebase/src/main/java/edu/fatec/Porygon/service/NoticiaService.java
- codebase/src/main/java/edu/fatec/Porygon/service/PortalService.java
- codebase/src/main/java/edu/fatec/Porygon/service/TagScrapperService.java
- codebase/src/main/java/edu/fatec/Porygon/service/TagService.java
Objetivo é otimizar o sistema para entrega final.
Métodos a serem removidos 
```
// Não deletamos portal apenas o desativamos.
public void deletar(Integer id) {
Portal portal = portalRepository.findById(id)
.orElseThrow(() -> new RuntimeException("Portal não encontrado"));
portal.setTags(new HashSet<>());
portalRepository.save(portal);
portalRepository.deleteById(id);
}
// As listagem ocorrem no metodo otimizado, naõ sendo necessarico metodos proprios e indepedentes
`public List<Noticia> listarNoticias() {
return noticiaRepository.findAll();
}
public List<Noticia> listarNoticiasPorData(LocalDate dataInicio, LocalDate dataFim) {
return noticiaRepository.searchNewsByData(dataInicio, dataFim);
}
public List<Noticia> listarNoticiasPorTags(List<Integer> tagIds) {
return …
```
> PYG-122 PYG-128 refactor/fix: trazendo Async para outros métodos
